-- PG-R-01：運動 session 摘要（activity-running-gallery 3.2／7、walk-run-tracking 3、SD 13／16）。
-- 只存摘要：內部整數毫米／毫秒／步數／毫 kcal；原始 GPS 與健康紀錄不進後端。
-- 去重鍵 (wallet, origin, external_record_id, source_revision)；同鍵較新 revision 取代、較舊拒絕；刪除留 tombstone。
CREATE TABLE IF NOT EXISTS workout_sessions (
  session_id            UUID PRIMARY KEY,
  wallet                TEXT NOT NULL,
  sport                 TEXT NOT NULL,
  environment           TEXT NOT NULL DEFAULT 'unknown',
  origin                TEXT NOT NULL,
  source_id             TEXT NOT NULL,
  external_record_id    TEXT NOT NULL,
  source_revision       INTEGER NOT NULL DEFAULT 1,
  started_at            TIMESTAMPTZ NOT NULL,
  ended_at              TIMESTAMPTZ NOT NULL,
  elapsed_ms            BIGINT NOT NULL,
  paused_ms             BIGINT NOT NULL DEFAULT 0,
  status                TEXT NOT NULL DEFAULT 'saved',
  quality               TEXT NOT NULL,
  rules_version         INTEGER NOT NULL,
  distance_mm           BIGINT,
  distance_method       TEXT,
  steps                 INTEGER,
  active_energy_mkcal   BIGINT,
  energy_method         TEXT,
  total_energy_mkcal    BIGINT,
  step_length_mm        INTEGER,
  pb_eligible           BOOLEAN NOT NULL DEFAULT false,
  possible_duplicate_of UUID REFERENCES workout_sessions(session_id),
  review_reasons        JSONB NOT NULL DEFAULT '[]',
  extras                JSONB NOT NULL DEFAULT '{}',
  request_hash          BYTEA NOT NULL,
  revision              INTEGER NOT NULL DEFAULT 1,
  imported_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at            TIMESTAMPTZ,
  UNIQUE (wallet, origin, external_record_id),
  CONSTRAINT workout_sport_ck CHECK (sport IN ('run', 'walk')),
  CONSTRAINT workout_env_ck CHECK (environment IN ('outdoor', 'indoor', 'unknown')),
  CONSTRAINT workout_origin_ck CHECK (origin IN ('health_connect', 'device', 'gps', 'organizer', 'manual')),
  CONSTRAINT workout_status_ck CHECK (status IN ('saved', 'needs_review', 'invalid', 'deleted')),
  CONSTRAINT workout_quality_ck CHECK (quality IN ('complete', 'partial', 'estimated', 'needs_review', 'invalid')),
  CONSTRAINT workout_distance_method_ck CHECK (distance_method IS NULL OR distance_method IN ('device', 'gps', 'estimated', 'organizer')),
  CONSTRAINT workout_energy_method_ck CHECK (energy_method IS NULL OR energy_method IN ('device', 'estimated', 'total')),
  CONSTRAINT workout_time_ck CHECK (ended_at > started_at AND elapsed_ms > 0 AND elapsed_ms <= 604800000 AND paused_ms >= 0 AND paused_ms < elapsed_ms),
  CONSTRAINT workout_bounds_ck CHECK ((distance_mm IS NULL OR distance_mm BETWEEN 0 AND 1000000000) AND (steps IS NULL OR steps BETWEEN 0 AND 1000000) AND (active_energy_mkcal IS NULL OR active_energy_mkcal BETWEEN 0 AND 100000000) AND (total_energy_mkcal IS NULL OR total_energy_mkcal BETWEEN 0 AND 100000000) AND (step_length_mm IS NULL OR step_length_mm BETWEEN 300 AND 2000)),
  CONSTRAINT workout_hash_len_ck CHECK (octet_length(request_hash) = 32)
);
CREATE INDEX IF NOT EXISTS workout_sessions_wallet_idx ON workout_sessions (wallet, started_at DESC) WHERE deleted_at IS NULL;
