[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
neonshift_core = "5vTs2vGPuADyCLtxkXpWQpuK25XoTihJ41drGKmfBjAf"

[programs.localnet]
neonshift_core = "6MhVoQHdEpY2hqkaNJMkT2vHWakfnGfEYDgCtJzh6ENA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["neonshift-core"]

[scripts]
test = "cargo test -p neonshift-core"

[hooks]
